/**
 * Screen: Home (workspace card grid)
 * Design System: [[design-system/index]]
 * Components: [[design-system/components/workspace-card]] · [[design-system/components/page-header]]
 * Generated by: /design-app — Phase 0 (mock data; backend lands in agent-runtime Phase 2)
 */
"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { ChevronRight } from "lucide-react";
import {
  WorkspaceCard,
  PageHeader,
} from "@/components/charm";
import { MOCK_WORKSPACES, getGlobalSummary } from "@/lib/mock/charm";

export default function HomePage() {
  const router = useRouter();
  const summary = React.useMemo(() => getGlobalSummary(), []);

  const greeting = greetByHour(new Date());

  return (
    <div className="px-8 py-8 max-w-7xl w-full mx-auto">
      <PageHeader
        kicker="Charm operator"
        title={`${greeting}, Elliott.`}
        subtitle={
          summary.totalPendingRecommendations > 0
            ? `${summary.totalPendingRecommendations} pending recommendation${
                summary.totalPendingRecommendations === 1 ? "" : "s"
              } across ${summary.needsAttention} workspace${
                summary.needsAttention === 1 ? "" : "s"
              } need your nod. ${summary.totalAgentsActive} agents on duty.`
            : `All workspaces healthy. ${summary.totalAgentsActive} agents on duty across ${summary.workspaceCount} workspaces.`
        }
        actions={
          summary.totalPendingRecommendations > 0 ? (
            <a
              href="/recommendations"
              className="inline-flex items-center gap-1.5 h-9 px-4 rounded-md text-sm font-medium bg-amber text-ink border-[1.5px] border-ink hover:shadow-flat-sm focus-visible:shadow-flat-sm transition-shadow"
            >
              Open mailbox
              <ChevronRight className="h-4 w-4" aria-hidden="true" />
            </a>
          ) : undefined
        }
      />

      <section aria-label="Workspaces" className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
        {MOCK_WORKSPACES.map((workspace) => (
          <WorkspaceCard
            key={workspace.id}
            workspace={workspace}
            onOpen={(id) => router.push(`/workspaces/${id}`)}
          />
        ))}
      </section>
    </div>
  );
}

function greetByHour(d: Date): string {
  const h = d.getHours();
  if (h < 5) return "Late night";
  if (h < 12) return "Morning";
  if (h < 17) return "Afternoon";
  if (h < 21) return "Evening";
  return "Evening";
}
